// AUTO-GENERATED by transformerWorker Step 4 — about page content data.
// The template's src/pages/about.astro imports this and passes it to ContentPage.
// Placeholder values below ensure the template builds standalone.

export const aboutData = [
  {
    type: 'navbar',
    data: {
      logo: 'Logo',
      links: [],
      cta: null,
    },
  },
  {
    type: 'hero',
    data: {
      headline: 'About Us',
      subheadline: 'Learn more about who we are and what we do.',
    },
  },
  {
    type: 'text',
    data: {
      title: 'Our Story',
      body: '<p>We are a company dedicated to delivering excellence. Our team brings years of experience and passion to every project we undertake.</p>',
    },
  },
  {
    type: 'features',
    data: {
      title: 'Our Values',
      subtitle: 'The principles that guide everything we do.',
      items: [
        { title: 'Quality', description: 'We never compromise on the quality of our work.' },
        { title: 'Innovation', description: 'We embrace new ideas and technologies.' },
        { title: 'Integrity', description: 'We do the right thing, always.' },
      ],
    },
  },
  {
    type: 'footer',
    data: {
      copyright: '',
      links: [],
    },
  },
];
